"""Tier B — perception replay over the committed recordings corpus (L1).

Feeds the PNGs under ``skills/golden/recordings/<run_id>/`` through the real
``Perceptor.perceive()`` and asserts the reconstruction matches the committed
``expected_scenes.jsonl`` baseline within ``SceneTolerance``. This is the
offline per-PR guard for perception regressions (OCR / scene classification /
letterbox crop). Design: ``docs/design/log_sim_replay_regression.md`` §5.

Baseline + tolerance provenance (B.0 characterization, 2026-06-10):

- ``expected_scenes.jsonl`` is generated by **current** perception code and
  human-reviewed — NOT the scene recorded at capture time. The 2026-06-01
  App Store recording captured the since-fixed settings-detail
  misclassification (``page_id='settings/Apps'``), so replay-vs-recorded would
  assert the old bug. Regenerate the baseline (and re-review) whenever
  perception behavior changes intentionally.
- Two tolerance profiles, set per recording in ``expected_scenes.jsonl``:
  - ``full`` (640x990 pre-cropped recording): repeated perceives of the same
    frame were exactly deterministic (text jaccard 1.0, box IoU 1.0, count
    delta 0) on the baseline host.
  - ``classification_only`` (raw 1920x1080 recording): letterbox-crop
    detection jitters a few px between perceives, flapping edge OCR (observed
    same-frame jaccard as low as 0.51) — so only ``page_id``/``scene_type``
    are gated. For the App Store recording that classification gate IS the
    payload: it freezes the fixed behavior (``page_id=None`` /
    ``scene_type='unknown'``); reintroducing the first-match settings cascade
    bug flips it back to ``settings/Apps`` and fails this test.
- Apple Vision's OCR output is NOT stable across macOS versions (CI's
  macos-latest produced same-frame jaccard 0.59 against a macOS 26.5
  baseline while page_id/scene_type held). Each recording carries the
  baseline host's version in ``baseline_env.json``; the ``full`` text/IoU
  profile applies only where ``platform.mac_ver()`` matches — elsewhere every
  recording is gated on classification (page_id + scene_type), which is the
  cross-version-stable, verifier-relevant contract.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from glassbox.cognition import Box, Scene, UIElement
from glassbox.memory.recording import _scene_from_event
from glassbox.perception.recording_source import RecordingFrameSource
from glassbox.perception.replay_assert import SceneTolerance, compare_scenes

RECORDINGS_ROOT = Path(__file__).resolve().parents[1] / "golden" / "recordings"

# Margins over the observed-deterministic baseline (see module docstring).
FULL_TOLERANCE = SceneTolerance(
    text_jaccard_min=0.85,
    element_count_delta_max=5,
    box_iou_min=0.5,
)
CLASSIFICATION_TOLERANCE = SceneTolerance(
    text_jaccard_min=0.0,
    element_count_delta_max=10_000,
    box_iou_check=False,
)
PROFILE_TOLERANCES = {
    "full": FULL_TOLERANCE,
    "classification_only": CLASSIFICATION_TOLERANCE,
}


def _recording_dirs() -> list[Path]:
    if not RECORDINGS_ROOT.is_dir():
        return []
    return sorted(p for p in RECORDINGS_ROOT.iterdir() if (p / "expected_scenes.jsonl").exists())


def _expected_entries(rec_dir: Path) -> list[dict]:
    lines = (rec_dir / "expected_scenes.jsonl").read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


def _baseline_env_matches(rec_dir: Path) -> bool:
    """True when this host's macOS matches the baseline generation host —
    only then are the full text/IoU tolerances meaningful (Vision OCR output
    differs across macOS versions)."""
    import platform

    env_path = rec_dir / "baseline_env.json"
    if not env_path.exists():
        return False
    baseline = json.loads(env_path.read_text(encoding="utf-8")).get("baseline_mac_ver")
    return bool(baseline) and platform.mac_ver()[0] == baseline


def _vision_ocr_available() -> bool:
    try:  # macOS-only (PyObjC / Vision.framework)
        from glassbox.cognition.ocr_vision import _import_vision

        _import_vision()
        return True
    except Exception:
        return False


@pytest.mark.smoke
def test_committed_recordings_corpus_is_walkable_and_scene_paired():
    """Corpus contract — no OCR needed, runs on any platform."""
    rec_dirs = _recording_dirs()
    assert rec_dirs, "no committed recordings under skills/golden/recordings"
    for rec_dir in rec_dirs:
        src = RecordingFrameSource(rec_dir)
        expected = _expected_entries(rec_dir)
        assert expected, f"{rec_dir.name}: empty expected_scenes.jsonl"
        seqs = []
        while True:
            seqs.append(src.current_seq)
            frame = src.snapshot()
            assert frame.img is not None and frame.img.size > 0
            if not src.advance():
                break
        assert seqs == [e["snapshot_seq"] for e in expected], (
            f"{rec_dir.name}: expected_scenes.jsonl seqs do not match the recording walk"
        )
        # every walked frame also has the original recorded observe-scene
        assert set(seqs) <= set(src.scene_by_seq), (
            f"{rec_dir.name}: recorded observe scenes missing for some frames"
        )
        for entry in expected:
            assert entry["profile"] in PROFILE_TOLERANCES
            # the baseline scene must round-trip through the Scene model
            assert _scene_from_event(entry) is not None
        src.close()


@pytest.mark.smoke
@pytest.mark.parametrize(
    "rec_dir", _recording_dirs(), ids=lambda p: p.name if isinstance(p, Path) else str(p)
)
def test_recorded_frames_reconstruct_expected_scenes(rec_dir):
    """The real perception gate: replay PNGs through perceive() and compare."""
    if not _vision_ocr_available():
        pytest.skip("Apple Vision OCR unavailable (non-macOS)")
    from glassbox.config import AgentConfig
    from glassbox.runtime import build_phone

    src = RecordingFrameSource(rec_dir)
    # Hermetic config: do NOT inherit .env (a stray GLASSBOX_REPLAY_DIR or
    # icon/VLM flags would change the pipeline under test).
    cfg = AgentConfig(_env_file=None, phone_model="ipad_mini_7")
    runtime = build_phone(source=src, cfg=cfg)
    phone = runtime.phone
    # One OCR per frame: disable the perceive cache (0.0 = documented disable;
    # the cache would return stale Scenes and desync the per-seq cursor).
    phone.perceive_cache_diff = 0.0

    failures: list[str] = []
    expected_by_seq = {e["snapshot_seq"]: e for e in _expected_entries(rec_dir)}
    full_profile_valid = _baseline_env_matches(rec_dir)
    while True:
        seq = src.current_seq
        entry = expected_by_seq[seq]
        expected_scene = _scene_from_event(entry)
        if hasattr(phone, "invalidate_perceive_cache"):
            phone.invalidate_perceive_cache()
        replayed = phone.perceive()
        profile = entry["profile"] if full_profile_valid else "classification_only"
        tol = PROFILE_TOLERANCES[profile]
        report = compare_scenes(expected_scene, replayed, tol)
        if not report.ok:
            failures.append(f"seq {seq}:\n{report.explain()}")
        if not src.advance():
            break
    src.close()
    assert not failures, f"{rec_dir.name}: {len(failures)} frame(s) drifted:\n" + "\n".join(failures)


# —— compare_scenes unit coverage (synthetic, cross-platform) ─────


def _scene(page_id, scene_type, items):
    return Scene(
        frame_id=0,
        timestamp=0.0,
        viewport_size=(640, 990),
        page_id=page_id,
        scene_type=scene_type,
        elements=[
            UIElement(text=t, type="text", box=Box(x=x, y=y, w=w, h=h), confidence=1.0)
            for (t, x, y, w, h) in items
        ],
    )


@pytest.mark.smoke
def test_compare_scenes_passes_on_identical_scene():
    scene = _scene("settings/Overlay", "settings_detail", [("Item Names", 10, 10, 100, 20)])
    report = compare_scenes(scene, scene, SceneTolerance())
    assert report.ok, report.explain()


@pytest.mark.smoke
def test_compare_scenes_hard_fails_on_page_id_drift():
    rec = _scene("settings/Overlay", "settings_detail", [("Item Names", 10, 10, 100, 20)])
    rep = _scene("settings/Apps", "settings_detail", [("Item Names", 10, 10, 100, 20)])
    report = compare_scenes(rec, rep, SceneTolerance())
    assert not report.ok
    assert any("page_id" in f for f in report.failures)


@pytest.mark.smoke
def test_compare_scenes_hard_fails_on_scene_type_drift():
    rec = _scene(None, "unknown", [("Candy Crush Saga", 10, 10, 100, 20)])
    rep = _scene(None, "settings_detail", [("Candy Crush Saga", 10, 10, 100, 20)])
    report = compare_scenes(rec, rep, SceneTolerance())
    assert not report.ok
    assert any("scene_type" in f for f in report.failures)


@pytest.mark.smoke
def test_compare_scenes_tolerates_minor_text_jitter_but_fails_major():
    rows = [(f"row {i}", 10, 10 + 30 * i, 100, 20) for i in range(20)]
    rec = _scene("p", "settings_detail", rows)
    # one of 20 texts OCR-garbled: jaccard 19/21 ≈ 0.905 ≥ 0.85 → tolerated
    minor = _scene("p", "settings_detail", [*rows[:19], ("rovv 19", 10, 580, 100, 20)])
    report = compare_scenes(rec, minor, SceneTolerance())
    assert report.ok, report.explain()
    major = _scene("p", "settings_detail", [("garbled", 10, 10, 100, 20)])
    report = compare_scenes(rec, major, SceneTolerance(element_count_delta_max=10_000))
    assert not report.ok
    assert any("jaccard" in f for f in report.failures)


@pytest.mark.smoke
def test_compare_scenes_fails_on_moved_box():
    rec = _scene("p", "settings_detail", [("Camera", 10, 100, 100, 20)])
    rep = _scene("p", "settings_detail", [("Camera", 10, 600, 100, 20)])
    report = compare_scenes(rec, rep, SceneTolerance())
    assert not report.ok
    assert any("IoU" in f for f in report.failures)
